#!/usr/bin/env python3
"""Generate checked-in focused workflow reference views from canonical sources."""

from __future__ import annotations

import os
import sys
from dataclasses import dataclass
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]
PHASES_SOURCE = Path(os.environ.get(
    "WORKFLOW_PHASES_SOURCE",
    REPO_ROOT / "skills/assistant-workflow/references/phases.md",
))
PLANS_SOURCE = Path(os.environ.get(
    "WORKFLOW_PLAN_SOURCE",
    REPO_ROOT / "skills/assistant-workflow/references/plan-template.md",
))
OUTPUT_ROOT = Path(os.environ.get(
    "WORKFLOW_FOCUSED_REFERENCE_ROOT",
    REPO_ROOT / "skills/assistant-workflow/references",
))

PHASE_HEADINGS = (
    "Shared Controller Decisions",
    "Progress Updates",
    "Phase: Discover",
    "Phase: Decompose",
    "Phase: Plan",
    "Phase: Design (UI/UX only, skip for backend)",
    "Phase: Build",
    "Phase: Review",
    "Phase: Document",
    "Phase: Preparation Completion",
)
PLAN_HEADINGS = (
    "Small Tasks — Inline Plan (`plan_mode=inline`, `execution_intent != prepare_only`)",
    "Executable Task Packet (`execution_intent != prepare_only`)",
    "Slice Manifest (`execution_intent != prepare_only`)",
    "Medium Tasks — Standard Plan (`execution_intent != prepare_only`)",
    "Large / Mega Tasks — Full Plan (`execution_intent != prepare_only`)",
    "Which tier to use",
    "Context Budget",
    "Pattern Retrieval",
)


@dataclass(frozen=True)
class MarkdownDocument:
    source: Path
    title: str
    preamble: str
    sections: dict[str, str]


def fail(message: str) -> None:
    raise ValueError(message)


def fence_marker(line: str) -> tuple[str, int] | None:
    stripped = line.lstrip(" ")
    if not stripped or stripped[0] not in "`~":
        return None
    marker = stripped[0]
    length = len(stripped) - len(stripped.lstrip(marker))
    return (marker, length) if length >= 3 else None


def closes_fence(line: str, active_fence: tuple[str, int]) -> bool:
    fence = fence_marker(line)
    if not fence or fence[0] != active_fence[0] or fence[1] < active_fence[1]:
        return False
    stripped = line.lstrip(" ")
    return not stripped[fence[1]:].strip()


def parse_document(source: Path, expected_sections: tuple[str, ...]) -> MarkdownDocument:
    try:
        text = source.read_text(encoding="utf-8")
    except OSError as error:
        fail(f"cannot read {source}: {error}")

    lines = text.splitlines(keepends=True)
    outer_headings: list[tuple[int, int, str]] = []
    active_fence: tuple[str, int] | None = None
    for index, line in enumerate(lines):
        fence = fence_marker(line)
        if active_fence:
            if closes_fence(line, active_fence):
                active_fence = None
            continue
        if fence:
            active_fence = fence
            continue
        if line.startswith("#"):
            level = len(line) - len(line.lstrip("#"))
            if level in (1, 2) and len(line) > level and line[level] == " ":
                outer_headings.append((index, level, line[level + 1:].strip()))
    if active_fence:
        fail(f"{source}: unclosed fenced Markdown block")

    h1 = [(index, heading) for index, level, heading in outer_headings if level == 1]
    if len(h1) != 1:
        fail(f"{source}: expected exactly one top-level title")
    h2 = [(index, heading) for index, level, heading in outer_headings if level == 2]
    headings = [heading for _, heading in h2]
    if len(headings) != len(set(headings)):
        fail(f"{source}: duplicate top-level section")
    if tuple(headings) != expected_sections:
        fail(f"{source}: unexpected or missing top-level sections")

    title_index, title = h1[0]
    first_section_index = h2[0][0]
    preamble = "".join(lines[title_index:first_section_index]).rstrip() + "\n"
    sections: dict[str, str] = {}
    for position, (start, heading) in enumerate(h2):
        end = h2[position + 1][0] if position + 1 < len(h2) else len(lines)
        sections[heading] = "".join(lines[start:end]).rstrip() + "\n"
    return MarkdownDocument(source=source, title=title, preamble=preamble, sections=sections)


def rendered_view(document: MarkdownDocument, headings: tuple[str, ...]) -> str:
    source_name = document.source.name
    header = (
        "<!-- Generated by tools/skills/sync-workflow-references.py; "
        f"source: {source_name}; do not edit. -->\n\n"
    )
    return header + document.preamble + "\n" + "\n\n".join(document.sections[name].rstrip() for name in headings) + "\n"


def views(phases: MarkdownDocument, plans: MarkdownDocument) -> dict[Path, str]:
    phase_common = ("Shared Controller Decisions", "Progress Updates")
    phase_views = {
        "discover": ("Phase: Discover",),
        "decompose": ("Phase: Decompose",),
        "plan": ("Phase: Plan",),
        "design": ("Phase: Design (UI/UX only, skip for backend)",),
        "build": ("Phase: Build",),
        "review": ("Phase: Review",),
        "document": ("Phase: Document",),
        "preparation-completion": ("Phase: Preparation Completion",),
    }
    generated = {
        Path("phases") / f"{name}.md": rendered_view(phases, phase_common + selected)
        for name, selected in phase_views.items()
    }
    common = ("Which tier to use", "Context Budget", "Pattern Retrieval")
    generated.update({
        Path("plans/prepare-only.md"): rendered_view(plans, common),
        Path("plans/small.md"): rendered_view(plans, (
            "Small Tasks — Inline Plan (`plan_mode=inline`, `execution_intent != prepare_only`)",
        ) + common),
        Path("plans/medium.md"): rendered_view(plans, (
            "Executable Task Packet (`execution_intent != prepare_only`)",
            "Slice Manifest (`execution_intent != prepare_only`)",
            "Medium Tasks — Standard Plan (`execution_intent != prepare_only`)",
        ) + common),
        Path("plans/large.md"): rendered_view(plans, (
            "Executable Task Packet (`execution_intent != prepare_only`)",
            "Slice Manifest (`execution_intent != prepare_only`)",
            "Medium Tasks — Standard Plan (`execution_intent != prepare_only`)",
            "Large / Mega Tasks — Full Plan (`execution_intent != prepare_only`)",
        ) + common),
    })
    return generated


def apply(generated: dict[Path, str]) -> None:
    for relative_path, content in generated.items():
        target = OUTPUT_ROOT / relative_path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")


def check(generated: dict[Path, str]) -> None:
    drifted = []
    for relative_path, content in generated.items():
        target = OUTPUT_ROOT / relative_path
        if not target.is_file() or target.read_text(encoding="utf-8") != content:
            drifted.append(str(target))
    if drifted:
        fail("generated workflow references drifted or are missing: " + ", ".join(drifted))


def main(argv: list[str]) -> int:
    if len(argv) != 2 or argv[1] not in {"--apply", "--check"}:
        print("Usage: sync-workflow-references.py --apply|--check", file=sys.stderr)
        return 2
    try:
        generated = views(
            parse_document(PHASES_SOURCE, PHASE_HEADINGS),
            parse_document(PLANS_SOURCE, PLAN_HEADINGS),
        )
        if argv[1] == "--apply":
            apply(generated)
            print(f"synced {len(generated)} workflow reference views")
        else:
            check(generated)
            print(f"checked {len(generated)} workflow reference views")
    except ValueError as error:
        print(f"Error: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
